spring:
  application:
    name: spring-properties

welcome:
  messages:
    hello:
      en: Hello, World!
      es: Hola, Mundo!
      fr: Bonjour, le Monde!
      pt: Olá, Mundo!
    welcome:
      en: Welcome to the Spring Properties Demo!
      es: Bienvenido al Demo de Propiedades de Spring!
      fr: Bienvenue dans la d?mo des propri?t?s de printemps!
      pt: Bem-vindo ao Demo de Propriedades de Primavera!
