spring:
  application:
    name: spring-properties

# Properties loaded with @ConfigurationProperties annotation
welcome:
  messages:
    purpose: Properties loaded with @ConfigurationProperties annotation
    hello:
      EN: Hello, World!
      ES: Hola, Mundo!
      FR: Bonjour, le Monde!
      PT: Olá, Mundo!
    welcome:
      EN: Welcome to the Spring Properties Demo!
      ES: Bienvenido al Demo de Propiedades de Spring!
      FR: Bienvenue dans la d?mo des propri?t?s de printemps!
      PT: Bem-vindo ao Demo de Propriedades de Primavera!
    nested:
      label: Nested Properties
      value: This is a nested property value
    list:
      - item1
      - item2
      - item3
      - item4
      - item5

# Properties loaded with @Value annotation

